# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhEeheEba54PsiKaH9Unp5SNB2liOMG_
"""



import re

# ============================================================
# JUVERISCAKES AI SHOPPING ASSISTANT
# Rule-Based Customer Purchase Assistant
# ============================================================


# ============================================================
# 1. PRODUCT LIBRARY
# ============================================================

products = {
    "ice cream": 1200,
    "meat pie": 1300,
    "zobo": 1400,
    "donut": 1500,
    "cupcake": 1500,
    "yogurt": 1800,
    "chapman": 2000,
    "popsicle": 2500,
    "shawarma": 4500,
    "pancakes": 6000,
    "bento cake": 8500,
    "7 inch cake": 13500,
    "milk cake":  3000

}

# Alternative ways customers may type product names
product_aliases = {
    "meatpie": "meat pie",
    "meatpies": "meat pie",
    "cup cake": "cupcake",
    "cup cakes": "cupcake"
}
# ============================================================
# 2. SPECIAL PRODUCTS / COMBOS
# ============================================================

combos = {
    "regular combo": 5000,
    "celebration combo": 15000
}


# ============================================================
# 3. QUANTITY WORDS
# ============================================================

quantity_words = {
    "one": 1,
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "seven": 7,
    "eight": 8,
    "nine": 9,
    "ten": 10
}


# ============================================================
# 4. CART
# ============================================================

cart = []

order_confirmed = False
payment_completed = False


# ============================================================
# 5. HELPER FUNCTION:
#    CONVERT AMOUNTS SUCH AS 2K, 3000, ₦3,000
# ============================================================

def extract_budget(text):

    text = text.lower().replace(",", "").replace("₦", "").strip()

    # Example: 2k
    match = re.search(r'(\d+(?:\.\d+)?)\s*k', text)

    if match:
        return int(float(match.group(1)) * 1000)

    # Example: 3000
    match = re.search(r'\b\d+\b', text)

    if match:
        return int(match.group())

    # Written amounts
    word_numbers = {
        "one thousand": 1000,
        "two thousand": 2000,
        "three thousand": 3000,
        "four thousand": 4000,
        "five thousand": 5000,
        "six thousand": 6000,
        "seven thousand": 7000,
        "eight thousand": 8000,
        "nine thousand": 9000,
        "ten thousand": 10000
    }

    for phrase, amount in word_numbers.items():
        if phrase in text:
            return amount

    return None


# ============================================================
# 6. HELPER FUNCTION:
#    FIND QUANTITY BEFORE A PRODUCT
# ============================================================

def get_quantity(text, product):

    # --------------------------------------------------------
    # Check numerical quantity
    # Examples:
    # 2 donuts
    # 5 meat pie
    # 10 yogurt
    # --------------------------------------------------------

    pattern = r'(\d+)\s*' + re.escape(product)
    match = re.search(pattern, text)

    if match:
        return int(match.group(1))

    # --------------------------------------------------------
    # Check written quantity
    # Examples:
    # two donuts
    # five meat pie
    # three yogurt
    # --------------------------------------------------------

    for word, number in quantity_words.items():

        phrase = word + " " + product

        if phrase in text:
            return number


    # --------------------------------------------------------
    # If no quantity is given, assume 1
    # --------------------------------------------------------

    return 1


# ============================================================
# 7. HELPER FUNCTION:
#    DISPLAY PRODUCT LIST
# ============================================================

def show_products():

    print("Bot: Here is our product menu:")
    print()

    for product, price in products.items():
        print(f"     {product.title()} - ₦{price:,}")

    print()
    print("Bot: Celebration combos start from ₦15,000.")


# ============================================================
# 8. HELPER FUNCTION:
#    SHOW CART
# ============================================================

def show_cart():

    if len(cart) == 0:

        print("Bot: 🛒 Your cart is empty.")
        print("Bot: Tell me what you would like to order.")

        return


    print("Bot: 🛒 Here is your current order:")
    print()

    total_cost = 0


    for product in products:

        quantity = cart.count(product)

        if quantity > 0:

            price = products[product]

            item_total = quantity * price

            print(
                f"     {quantity} x {product.title()} "
                f"= ₦{item_total:,}"
            )

            total_cost += item_total


    print()
    print("--------------------------------------")
    print(f"Bot: TOTAL = ₦{total_cost:,}")
    print("--------------------------------------")


# ============================================================
# 9. HELPER FUNCTION:
#    CALCULATE TOTAL
# ============================================================

def calculate_total():

    total = 0

    for product in cart:

        total += products[product]

    return total


# ============================================================
# 10. WELCOME MESSAGE
# ============================================================

print("==========================================")
print("       WELCOME TO JUVERISCAKES")
print("==========================================")
print("Bot: Hi! 👋 I'm the JuverisCakes AI")
print("Bot: Customer Purchase Assistant.")
print()
print("Bot: I can help you:")
print("     • Find products")
print("     • Choose treats and meals")
print("     • Find options for different occasions")
print("     • Build your shopping cart")
print("     • Calculate your total")
print("     • Confirm your order")
print("     • Process a simulated payment")
print()
print("Bot: Type 'bye' whenever you want to leave.")
print()


# ============================================================
# 11. MAIN CHATBOT LOOP
# ============================================================

while True:

    user_input = input("You: ").lower().strip()


    # ========================================================
    # EXIT
    # ========================================================

    if user_input in [
        "bye",
        "exit",
        "quit",
        "goodbye"
    ]:

        print()
        print("Bot: Thank you for visiting JuverisCakes! 😊")
        print("Bot: Have a lovely day!")
        break


    # ========================================================
    # GREETING
    # ========================================================

    elif user_input in [
        "hello",
        "hi",
        "hey",
        "good morning",
        "good afternoon",
        "good evening",
        "what's up"
    ]:

        print("Bot: Hello! 👋 Welcome to JuverisCakes.")
        print("Bot: What delicious treat can I help you find today?")


    # ========================================================
    # PRODUCT LIBRARY
    # ========================================================

    elif user_input in [
        "what do you sell",
        "what do you have",
        "show me your products",
        "show me your product",
        "what products do you have",
        "what can i buy",
        "menu",
        "show menu",
        "product list",
        "today's menu",
        "what is available",
        "what's available"
    ]:

        show_products()


    # ========================================================
    # BIRTHDAY / CELEBRATION
    # ========================================================

    elif any(word in user_input for word in [
        "birthday",
        "celebration",
        "celebrate",
        "sign out",
        "signout",
        "graduation",
        "convocation",
        "girlfriend day",
        "boyfriend day"
    ]):

        print("Bot: 🎉 Congratulations!")
        print("Bot: We have celebration options starting")
        print("     from ₦15,000.")
        print()
        print("Bot: Celebration combos can include:")
        print("     • Cake")
        print("     • Donuts or meat pies")
        print("     • Yogurt, zobo, or Chapman")
        print()
        print("Bot: Individual cake options include:")
        print("     • Bento cake - ₦8,500")
        print("     • 7-inch one-layer cake - ₦13,500")
        print("     • Cupcake - ₦1,500 each")


    # ========================================================
    # BREAKFAST
    # ========================================================

    elif any(word in user_input for word in [
        "breakfast",
        "morning food",
        "breakfast option",
        "morning"
    ]):

        print("Bot: ☀️ Good morning!")
        print("Bot: Our breakfast option is:")
        print("     Pancakes with sauce - ₦6,000")
        print("Bot: A yummy way to start your day! 🥞")


    # ========================================================
    # HUNGER / MEAL
    # ========================================================

    elif any(phrase in user_input for phrase in [
        "i am hungry",
        "i'm hungry",
        "im hungry",
        "i need food",
        "i want food",
        "something to eat",
        "i want something to eat",
        "i am famished",
        "i'm famished",
        "im famished",
        "i need something to eat",
        "tired and hungry"

    ]):

        print("Bot: You're hungry? I've got you! 😋")
        print("Bot: Here are some filling options:")
        print("     • Shawarma - ₦4,500")
        print("     • Pancakes with sauce - ₦6,000")
        print("     • Meat pie - ₦1,300")


    # ========================================================
    # SNACK / TREAT
    # ========================================================

    elif any(phrase in user_input for phrase in [
        "snack",
        "treat",
        "something small",
        "something yummy",
        "something sweet",
        "something to eat",
        "something tasty",
        "something light",
        "craving",
        "sweet tooth craving",
        "sweet"
    ]):

        print("Bot: 😋 Here are some tasty treat options:")
        print("     • Ice cream - ₦1,200")
        print("     • Meat pie - ₦1,300")
        print("     • Donut - ₦1,500")
        print("     • Cupcake - ₦1,500")
        print("     • Zobo - ₦1,400")
        print("     • Yogurt - ₦1,800")
        print("     • milk cake -₦3000 ")
        print("     • meat pie - ₦1,300")
        print("     • Donut - ₦1,500")


    # ========================================================
    # CHILDREN
    # ========================================================

    elif any(phrase in user_input for phrase in [
        "children",
        "kids",
        "child",
        "for my child",
        "for children"
    ]):

        print("Bot: 👧🧒 We have some fun options for children:")
        print("     • Ice cream - ₦1,200")
        print("     • Donut - ₦1,500")
        print("     • Cupcake - ₦1,500")
        print("     • Popsicle - ₦2,500")
        print("     • Yogurt - ₦1,800")


    # ========================================================
    # AFFORDABLE / BUDGET FRIENDLY
    # ========================================================

    elif any(phrase in user_input for phrase in [
        "something cheap",
        "something affordable",
        "budget friendly",
        "budget-friendly",
        "i am on a budget",
        "i'm on a budget",
        "cheap",
        "affordable",
        "pocket friendly",
        "not tear my pocket",
        "studently friendly"
    ]):

        print("Bot: No prblem! 😊")
        print("Bot: Here are some affordable options:")
        print("     • Ice cream - ₦1,200")
        print("     • Meat pie - ₦1,300")
        print("     • Zobo - ₦1,400")
        print("     • Donut - ₦1,500")
        print("     • Cupcake - ₦1,500")
        print("     • yogurt - ₦1800")


    # ========================================================
    # COMBOS
    # ========================================================

    elif any(phrase in user_input for phrase in [
        "combo",
        "combos",
        "combination",
        "meal deal"
    ]):

        print("Bot: 😋 Yes! We have:")
        print()
        print("Bot: 1. Regular Combo - ₦5,000")
        print("     Shawarma + ice cream, yogurt, or zobo")
        print()
        print("Bot: 2. Celebration Combo - from ₦15,000")
        print("     Cake + donuts or meat pies + a drink")


    # ========================================================
    # BUDGET SEARCH
    # ========================================================

    elif any(phrase in user_input for phrase in [
        "my budget",
        "i have",
        "i can spend",
        "budget is",
        "i can afford"
    ]):

        budget = extract_budget(user_input)

        if budget is None:

            print("Bot: Please tell me your budget.")
            print("Bot: For example: 'I have 2k' or")
            print("     'My budget is 3000 naira'.")

        else:

            print(f"Bot: Your budget is ₦{budget:,}.")
            print("Bot: Here are some options you can consider:")

            found_option = False

            for product, price in products.items():

                if price <= budget:

                    print(
                        f"     • {product.title()} - ₦{price:,}"
                    )

                    found_option = True

            if not found_option:

                print("Bot: Our lowest listed product is")
                print("     Ice cream - ₦1,200.")


    # ========================================================
    # REMOVE PRODUCT
    # ========================================================

    elif any(phrase in user_input for phrase in [
        "remove",
        "delete",
        "remove product",
        "delete product",
        "remove item",
        "delete item"
    ]):

        selected_product = None

        for product in products:

            if product in user_input:

                selected_product = product
                break


        if selected_product is None:

            print("Bot: Which product would you like to remove?")


        elif selected_product not in cart:

            print(
                f"Bot: {selected_product.title()} "
                "is not currently in your cart."
            )


        else:

            cart.remove(selected_product)

            print(
                f"Bot: One {selected_product} "
                "has been removed from your cart. 🛒"
            )


    # ========================================================
    # CLEAR CART
    # ========================================================

    elif user_input in [
        "clear my cart",
        "empty my cart",
        "cancel my order",
        "clear order",
        "empty cart",
        "cancel order",
        "clear cart",
        "delete my order",
        "delete my cart",
        "delete order",
        "delete cart"
    ]:

        cart.clear()

        print("Bot: Your cart has been cleared. 🛒")
        print("Bot: You can start a new order whenever you're ready.")


    # ========================================================
    # VIEW CART
    # ========================================================

    elif user_input in [
        "show my order",
        "show my cart",
        "my order",
        "my cart",
        "what is in my cart",
        "order summary",
        "cart summary",
        "view cart",
        "view my order",
        "show my shopping cart",
        "what is in my shopping cart",
        "what is my order",
        "what is in my order"
    ]:

        show_cart()


    # ========================================================
    # FINAL ORDER CONFIRMATION
    # ========================================================

    elif user_input in [
        "confirm",
        "confirm order",
        "yes confirm",
        "i want to confirm",
        "confirm my order"
    ]:

        if len(cart) == 0:

            print("Bot: Your cart is empty. 🛒")
            print("Bot: Please add something before confirming.")

        else:

            total_cost = calculate_total()

            print()
            print("Bot: 🧾 FINAL ORDER SUMMARY")
            print("--------------------------------------")

            for product in products:

                quantity = cart.count(product)

                if quantity > 0:

                    price = products[product]
                    item_total = quantity * price

                    print(
                        f"{quantity} x {product.title()} "
                        f"= ₦{item_total:,}"
                    )

            print("--------------------------------------")
            print(f"TOTAL = ₦{total_cost:,}")
            print("--------------------------------------")

            order_confirmed = True

            print()
            print("Bot: ✅ Order confirmed!")
            print("Bot: Your order has been recorded.")
            print("Bot: Would you like to proceed to payment?")
            print("Bot: Type 'pay' to continue.")


    # ========================================================
    # PAYMENT
    # ========================================================

    elif user_input in [
        "pay",
        "payment",
        "make payment",
        "proceed to payment",
        "pay now"
    ]:

        if not order_confirmed:

            print("Bot: Please confirm your order first.")
            print("Bot: Type 'confirm order' to continue.")

        else:

            total_cost = calculate_total()

            print()
            print("Bot: 💳 PAYMENT")
            print("--------------------------------------")
            print(f"Bot: Amount to pay = ₦{total_cost:,}")
            print()
            print("Bot: This is a simulated payment system")
            print("Bot: for the chatbot project.")
            print()
            print("Bot: Choose a payment method:")
            print("     1. Card")
            print("     2. Bank Transfer")
            print("     3. Cash on Delivery")


    # ========================================================
    # PAYMENT METHOD
    # ========================================================

    elif user_input in [
        "1",
        "card",
        "pay with card",
        "card payment"
    ]:

        if not order_confirmed:

            print("Bot: Please confirm your order first.")

        else:

            payment_completed = True

            print("Bot: 💳 Card payment selected.")
            print("Bot: Payment processing...")
            print("Bot: ✅ Payment successful!")
            print("Bot: Thank you for your order,")
            print("     and thank you for choosing JuverisCakes! 😊")


    elif user_input in [
        "2",
        "bank transfer",
        "transfer",
        "pay by transfer"
    ]:

        if not order_confirmed:

            print("Bot: Please confirm your order first.")

        else:

            payment_completed = True

            print("Bot: 🏦 Bank transfer selected.")
            print("Bot: Payment processing...")
            print("Bot: ✅ Payment successful!")
            print("Bot: Thank you for your order! 😊")


    elif user_input in [
        "3",
        "cash",
        "cash on delivery",
        "pay cash"
    ]:

        if not order_confirmed:

            print("Bot: Please confirm your order first.")

        else:

            payment_completed = True

            print("Bot: 💵 Cash on Delivery selected.")
            print("Bot: Your order has been placed.")
            print("Bot: Payment will be made upon delivery.")
            print("Bot: Thank you for ordering from JuverisCakes! 😊")

    # Start a fresh order after successful payment
    elif payment_completed:
        cart.clear()
        order_confirmed = False
        payment_completed = False

        print()
        print("Bot: 🛒 Your previous order is complete.")
        print("Bot: You can start a new order whenever you're ready.")

    # ========================================================
    # ADD PRODUCTS TO CART
    # ========================================================

    elif (
        any(product in user_input for product in products)
        or any(alias in user_input for alias in product_aliases)
    ):

        found_products = []


        # ----------------------------------------------------
        # Find every product mentioned
        # ----------------------------------------------------

        for product in products:

            if product in user_input:

                found_products.append(product)


        # ----------------------------------------------------
        # Check alternative product names
        # ----------------------------------------------------

        for alias, actual_product in product_aliases.items():
            if alias in user_input:
                if actual_product not in found_products:
                    found_products.append(actual_product)

        # ----------------------------------------------------
        # Process every product
        # ----------------------------------------------------

        for selected_product in found_products:

            quantity = get_quantity(user_input, selected_product)

            # Also check quantity when customer uses an alias
            for alias, actual_product in product_aliases.items():
                if actual_product == selected_product:
                    alias_quantity = get_quantity(user_input, alias)
                    if alias_quantity != 1:
                        quantity = alias_quantity


            # Add product quantity to cart

            for i in range(quantity):

                cart.append(selected_product)


            price = products[selected_product]

            item_total = quantity * price


            print(
                f"Bot: {quantity} x "
                f"{selected_product.title()} "
                f"added to your cart! 🛒"
            )

            print(
                f"Bot: {selected_product.title()} "
                f"= ₦{price:,} each"
            )

            print(
                f"Bot: Item total = ₦{item_total:,}"
            )


        # ----------------------------------------------------
        # Show updated cart total
        # ----------------------------------------------------

        current_total = calculate_total()

        print()
        print(
            f"Bot: Your current cart total is "
            f"₦{current_total:,}."
        )


    # ========================================================
    # YES / NO RESPONSES
    # ========================================================

    elif user_input in [
        "yes",
        "yeah",
        "yep"
    ]:

        if len(cart) > 0:

            print("Bot: Great! 😊")
            print("Bot: Your order is ready.")
            print("Bot: Type 'confirm order' to confirm it.")

        else:

            print("Bot: What would you like to order?")


    elif user_input in [
        "no",
        "no thanks",
        "not now"
    ]:

        print("Bot: No problem! 😊")
        print("Bot: You can continue browsing our products.")


    # ========================================================
    # UNKNOWN INPUT
    # ========================================================

    else:

        print("Bot: I'm still learning. 😊")
        print("Bot: You can ask me things like:")
        print("     • What do you sell?")
        print("     • I'm hungry")
        print("     • I want a snack")
        print("     • I have a birthday")
        print("     • I want breakfast")
        print("     • I have 2k")
        print("     • I want 2 donuts and 3 yogurts")
        print("     • Show my cart")
        print("     • Remove yogurt")
        print("     • Confirm order")
        print("     • Pay")

from google.colab import drive
drive.mount('/content/drive')